//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:09:33 ¤W¤È TST 
//


package com.ericstudio.webstore.domain.brick.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getSetsResult" type="{http://brickset.com/api/}ArrayOfSets" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getSetsResult"
})
@XmlRootElement(name = "getSetsResponse")
public class GetSetsResponse {

    protected ArrayOfSets getSetsResult;

    /**
     * Gets the value of the getSetsResult property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSets }
     *     
     */
    public ArrayOfSets getGetSetsResult() {
        return getSetsResult;
    }

    /**
     * Sets the value of the getSetsResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSets }
     *     
     */
    public void setGetSetsResult(ArrayOfSets value) {
        this.getSetsResult = value;
    }

}
