//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 10:09:33 ¤W¤È TST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://brickset.com/api/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ericstudio.webstore.domain.brick.v2;
